# 

name: Run Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Check formatting with black
        run: |
          black  pil_font_maker --check --diff
      - name: Lint with flake8
        run: |
          flake8 pil_font_maker 
      - name: Lint with mypy
        run: |
          mypy   pil_font_maker 
      - name: Lint with pylint
        run: |
          pylint pil_font_maker
