# 

name: Run Tests

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements-workflow.txt
      - name: Check formatting with black
        if: always()
        run: |
          black  pil_font_maker --check --diff
      - name: Lint with flake8
        if: always()
        run: |
          flake8 pil_font_maker 
      - name: Lint with mypy
        if: always()
        run: |
          mypy   pil_font_maker 
      - name: Lint with pylint
        if: always()
        run: |
          pylint pil_font_maker
